name: CI

on:
  push:
    branches: action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux package
        uses: mijailr/arch-makepkg-action@v1