name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: datakrama/archlinux-package-action@v1
        with:
          path: $GITHUB_WORKSPACE/package
          flags: '-s'
          namcap: false